INSERT INTO EMPLOYEE_DETAILS
SELECT A.EMP_ID, A.EMP_NAME, A.DEPT_NM, B.BUS_UNIT_NM,B.LOCATION AS BASE_LOCATION, C.GRADE_PAY, 
A.INCENTIVE_PAY, (C.GRADE_PAY+A.INCENTIVE_PAY*A.PERFORMANCE_FACTOR) AS TOTAL_PAY, A.DATE::MONTH , 'PERM' AS EMP_TYPE
FROM CONTRACT_EMP_STG A, LEFT JOIN BUS_UNIT B ON A.BUS_UNIT_CD=B.BUS_UNIT_CD LEFT JOIN DEPT ON A.DEPT=C.DEPT AND A.GRADE=B.GRADE WHERE A.DELETE_DTM IS NOT NULL;